name: Demo

run-name: ${{ github.actor }} is testing out GitHub Actions

on:

  push:

  workflow_dispatch:

jobs:

  Explore-GitHub-Actions:

    runs-on: self-hosted

    steps:

      - run: echo "secrets a ${{ secrets.MY_SECRET_NAME }} ."
